language: c

compiler:
  - clang
  - gcc

env:
  - BLD=cmake
  - BLD=autotools

addons:
  apt:
    packages:
      - libusb-dev
      - cmake
      - libcutter-dev

install:
  - git clone https://github.com/nfc-tools/libnfc
  - ./.travis-ci-build libnfc
script: ./.travis-ci-build .
